---
- name: Move Site24x7 logs on Windows
  hosts: 10.1.0.62
  gather_facts: no

  tasks:
    - name: Move logs using robocopy
      win_command: >
        robocopy
        "D:\Site24x7_logs\Logs"
        "E:\Site24x7 Logs\Logs"
        /E /MOVE /R:2 /W:2
      register: robocopy_result
      failed_when: robocopy_result.rc >= 8
