---
- name: Copy Site24x7 logs on Windows
  hosts: windows
  tasks:
    - name: Copy logs using robocopy
      ansible.windows.win_robocopy:
        src: 'C:\Program Files (x86)\Site24x7\WinAgent\monitoring\logs'
        dest: 'D:\Site24x7_logs\Logs'
        flags: /E /R:2 /W:2
